export const networks = [
    { name: 'Ethereum', rpcBase: 'https://rpc.ankr.com/eth' },
    { name: 'Binance Smart Chain', rpcBase: 'https://bsc-dataseed.binance.org' },
    { name: 'Polygon', rpcBase: 'https://polygon-rpc.com' },
    { name: 'Avalanche C-Chain', rpcBase: 'https://api.avax.network/ext/bc/C/rpc' },
    { name: 'Arbitrum One', rpcBase: 'https://arb1.arbitrum.io/rpc' },
    { name: 'Optimism', rpcBase: 'https://mainnet.optimism.io' },
    { name: 'Fantom Opera', rpcBase: 'https://rpc.ftm.tools' },
    { name: 'Cronos', rpcBase: 'https://evm-cronos.crypto.org' },
    { name: 'Base', rpcBase: 'https://mainnet.base.org' },
    { name: 'Blast', rpcBase: 'https://mainnet-rpc.blastapi.io' },
    { name: 'Aurora', rpcBase: 'https://mainnet.aurora.dev' },
    { name: 'Polygon zkEVM (ZKSync Era)', rpcBase: 'https://mainnet.era.zksync.io' },
    { name: 'Mantle', rpcBase: 'https://rpc.mantle.xyz' },
    { name: 'PulseChain', rpcBase: 'https://rpc.pulsechain.com' },
    { name: 'Ethereum Classic', rpcBase: 'https://rpc.ankr.com/etc' },
    { name: 'EthereumPoW', rpcBase: 'https://mainnet.ethereumpow.org' },
    { name: 'Gnosis Chain', rpcBase: 'https://rpc.gnosischain.com' },
    { name: 'Kava EVM', rpcBase: 'https://evm.kava.io' },
    { name: 'Telos EVM', rpcBase: 'https://mainnet.telos.net/evm' },
    { name: 'RSK', rpcBase: 'https://public-node.rsk.co' },
    { name: 'Energy Web Chain', rpcBase: 'https://rpc.energyweb.org' },
    { name: 'Chiliz EVM', rpcBase: 'https://rpc.chiliz.net' },
    { name: 'Dischain (EthereumFair)', rpcBase: 'https://rpc.ethereumfair.org' },
    { name: 'Flare', rpcBase: 'https://flare-api.flare.network/ext/C/rpc' },
    { name: 'Moonbeam', rpcBase: 'https://rpc.api.moonbeam.network' },
    { name: 'Moonriver', rpcBase: 'https://rpc.api.moonriver.network' },
    { name: 'XDC Network', rpcBase: 'https://rpc.xinfin.network' },
    { name: 'Shibarium', rpcBase: 'https://rpc.shibarium.io' },
    { name: 'ApeChain', rpcBase: 'https://rpc.apechain.net' },
    { name: 'Canxium EVM', rpcBase: 'https://rpc.canxium.network' },
    { name: 'Boba Network', rpcBase: 'https://mainnet.boba.network' },
    { name: 'Metis Andromeda', rpcBase: 'https://andromeda.metis.io' },
    { name: 'OKExChain', rpcBase: 'https://exchainrpc.okex.org' },
    { name: 'Huobi ECO Chain', rpcBase: 'https://http-mainnet.hecochain.com' },
    { name: 'TomoChain', rpcBase: 'https://rpc.tomochain.com' },
    { name: 'Wanchain', rpcBase: 'https://rpc.wanchain.org' },
    { name: 'IoTeX', rpcBase: 'https://babel-api.mainnet.iotex.io' },
    { name: 'Oasis Emerald', rpcBase: 'https://emerald.oasis.dev' },
    { name: 'KuCoin Community Chain (KCC)', rpcBase: 'https://rpc-mainnet.kcc.network' },
    { name: 'Songbird', rpcBase: 'https://songbird.towolabs.com/rpc' },
    { name: 'Celo', rpcBase: 'https://forno.celo.org' },
    { name: 'Evmos', rpcBase: 'https://evmos-evm-rpc.polygon.io' },
    { name: 'Palm', rpcBase: 'https://palm-mainnet.public.blastapi.io' },
    { name: 'Theta', rpcBase: 'https://eth-rpc-api.thetatoken.org/rpc' },
    { name: 'Meter', rpcBase: 'https://rpc.meter.io' },
    { name: 'Syscoin', rpcBase: 'https://rpc.syscoin.org' },
    { name: 'ThunderCore', rpcBase: 'https://mainnet-rpc.thundercore.com' },
    { name: 'Fuse', rpcBase: 'https://rpc.fuse.io' },
    { name: 'Canto', rpcBase: 'https://mainnode.plexnode.org:8545' },
    { name: 'Linea', rpcBase: 'https://rpc.linea.build' }
];