# .github/workflows/deploy.yml
name: Build & Deploy Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Generate config
        run: |
          mkdir -p js
          cat > js/networks.config.js <<EOF
          export const ETH_API_KEY = '${{ secrets.ETH_API_KEY }}';
          EOF

      - name: Build site
        run: |
          mkdir -p public
          cp index.html public/
          cp -R js public/js
          cp style.css public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
